import type { Metadata } from "next";

import "./globals.css";
import Header from "./ui/header";
import Footer from "./ui/footer";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Beaudy Ink",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-cinzel antialiased" suppressHydrationWarning={true}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
